import json
import glob

# This script compares the "answer sheet" generated by the GPT API with the "solution" produced by the fine-tuned model
# and calculates the accuracy. It is used to evaluate how well the fine-tuned model performs in comparison to the 
# answers generated by the GPT API.

def calculate_accuracy(list1, list2):
    matching_count = sum(1 for x, y in zip(list1, list2) if x == y)
    accuracy = (matching_count / len(list1)) * 100
    return accuracy

if __name__ == "__main__":
    answer = '../resource/data/gpt4_answer.json'
    with open(answer, 'r', encoding='utf-8') as f:
        list1 = json.load(f)
      
    file_paths = glob.glob('../answer/**/*', recursive=True)
    
    for checker in file_paths:
        with open(checker, 'r', encoding='utf-8') as file:
            data = json.load(file)
        list2 = [entry['output'] for entry in data]
        
        accuracy = calculate_accuracy(list1, list2)
        print(f"{checker} is Accuracy: {accuracy:.2f}%")